"use client";
import { useEffect, useState } from "react";
export default function NewsAdmin(){
  const [list,setList]=useState<any[]>([]); const [title,setTitle]=useState(""); const [err,setErr]=useState<string|null>(null);
  function load(){ const t=localStorage.getItem("cms_token"); if(!t){setErr("Not auth");return;} fetch(`${process.env.NEXT_PUBLIC_API_URL}/api/v1/admin/news`,{headers:{Authorization:`Bearer ${t}`,Accept:"application/json"}}).then(r=>r.json()).then(j=>setList(j.data.data??j.data??[])).catch(e=>setErr(e.message));}
  useEffect(()=>load(),[]);
  async function create(e:React.FormEvent){e.preventDefault(); const t=localStorage.getItem("cms_token"); const r=await fetch(`${process.env.NEXT_PUBLIC_API_URL}/api/v1/admin/news`,{method:"POST",headers:{Authorization:`Bearer ${t}`,"Content-Type":"application/json",Accept:"application/json"},body:JSON.stringify({title,excerpt:"E2E",content:"<p>body</p>",status:"draft"})}); const j=await r.json(); if(!r.ok){setErr(JSON.stringify(j));return;} setTitle(""); load();}
  async function publish(slug:string){ const t=localStorage.getItem("cms_token"); await fetch(`${process.env.NEXT_PUBLIC_API_URL}/api/v1/admin/news/${slug}/publish`,{method:"POST",headers:{Authorization:`Bearer ${t}`,Accept:"application/json"}}); load();}
  return <div><h1 className="font-serif text-xl font-bold">News</h1><form onSubmit={create} className="mt-4 flex gap-2 border bg-white p-4"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Title" className="flex-1 border px-3 py-2 text-sm" required/><button className="h-10 px-5 bg-slate-900 text-white text-sm">Create draft</button></form>{err&&<div className="mt-4 text-sm border bg-amber-50 p-3">{err}</div>}<div className="mt-6 border bg-white"><table className="w-full text-sm"><thead className="text-xs text-slate-500 border-b"><tr><th className="text-left px-4 py-2">Title</th><th className="text-left px-4 py-2">Status</th><th className="text-left px-4 py-2">Actions</th></tr></thead><tbody className="divide-y">{list.map((n:any)=><tr key={n.id}><td className="px-4 py-2 line-clamp-1">{n.title}</td><td className="px-4 py-2"><span className={`px-2 py-0.5 text-xs border ${n.status==="published"?"bg-green-50":"bg-amber-50"}`}>{n.status}</span></td><td className="px-4 py-2">{n.status!=="published"&&<button onClick={()=>publish(n.slug)} className="px-3 py-1 bg-amber-600 text-white text-xs">Publish</button>}</td></tr>)}</tbody></table>{!list.length&&<div className="p-6 text-center text-sm text-slate-500">No data</div>}</div></div>;
}
