"use client";
import { useEffect, useState } from "react";
export default function PagesAdmin(){
  const [list,setList]=useState<any[]>([]); const [title,setTitle]=useState(""); const [err,setErr]=useState<string|null>(null);
  function load(){ const t=localStorage.getItem("cms_token"); if(!t){setErr("Not auth");return;} fetch(`${process.env.NEXT_PUBLIC_API_URL}/api/v1/admin/pages`,{headers:{Authorization:`Bearer ${t}`,Accept:"application/json"}}).then(r=>r.json()).then(j=>setList(j.data.data??j.data??[])).catch(e=>setErr(e.message));}
  useEffect(()=>load(),[]);
  async function create(e:React.FormEvent){e.preventDefault(); const t=localStorage.getItem("cms_token"); const r=await fetch(`${process.env.NEXT_PUBLIC_API_URL}/api/v1/admin/pages`,{method:"POST",headers:{Authorization:`Bearer ${t}`,"Content-Type":"application/json",Accept:"application/json"},body:JSON.stringify({title,status:"draft",blocks:[{type:"hero",data:{heading:title,subheading:"Created via CMS"},sort_order:0},{type:"rich_text",data:{content:`<p>${title} body</p>`},sort_order:1}]})}); const j=await r.json(); if(!r.ok){setErr(JSON.stringify(j));return;} setTitle(""); load();}
  return <div><h1 className="font-serif text-xl font-bold">Pages & Blocks</h1><p className="text-sm text-slate-600 mt-1">Page builder JSON blocks → BlockRenderer (hero, rich_text, stats, cta, project_grid …)</p><form onSubmit={create} className="mt-4 flex gap-2 border bg-white p-4"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Page title" className="flex-1 border px-3 py-2 text-sm" required/><button className="h-10 px-5 bg-slate-900 text-white text-sm">Create with hero+rich</button></form>{err&&<div className="mt-4 text-sm border bg-amber-50 p-3">{err}</div>}<div className="mt-6 border bg-white"><table className="w-full text-sm"><thead className="text-xs text-slate-500 border-b"><tr><th className="text-left px-4 py-2">Title</th><th className="text-left px-4 py-2">Slug</th><th className="text-left px-4 py-2">Blocks</th></tr></thead><tbody className="divide-y">{list.map((p:any)=><tr key={p.id}><td className="px-4 py-2">{p.title}</td><td className="px-4 py-2 font-mono text-xs">{p.slug}</td><td className="px-4 py-2 text-xs">{p.blocks?.length??0}</td></tr>)}</tbody></table>{!list.length&&<div className="p-6 text-center text-sm text-slate-500">No pages</div>}</div></div>;
}
